// Mocks generated by Mockito 5.4.4 from annotations
// in vent_expense_pro/test/services/wallet_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vent_expense_pro/models/wallet_model.dart' as _i4;
import 'package:vent_expense_pro/repositories/wallet_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i2.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WalletModel>> getAllWallets() => (super.noSuchMethod(
        Invocation.method(
          #getAllWallets,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.WalletModel>>.value(<_i4.WalletModel>[]),
      ) as _i3.Future<List<_i4.WalletModel>>);

  @override
  _i3.Future<_i4.WalletModel?> getWallet(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [id],
        ),
        returnValue: _i3.Future<_i4.WalletModel?>.value(),
      ) as _i3.Future<_i4.WalletModel?>);

  @override
  _i3.Future<int> createWallet(_i4.WalletModel? wallet) => (super.noSuchMethod(
        Invocation.method(
          #createWallet,
          [wallet],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateWallet(_i4.WalletModel? wallet) => (super.noSuchMethod(
        Invocation.method(
          #updateWallet,
          [wallet],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteWallet(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWallet,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
