name: VentFit Build and Test CI (Android)

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: Run Tests
        run: flutter test

  build:
    name: Run Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Setup java environment to build android app
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    # Setup flutter environment
    - uses: actions/checkout@v3
    - name: Setup Flutter env
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true

    - name: Clean project
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get
    
    - name: Generate necessary annotation
      run: flutter pub run build_runner build
    
    # - name: Analyze dart code
    #   run: flutter analyze .
    
    - name: Build apk
      run: flutter build apk --debug --split-per-abi