name: VentFit Build and Test CI (Android)

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - name: Run Tests
        run: flutter test